version: "3.9"

services:
  backend:
    image: todotestcg.azurecr.io/todo-test-backend
    container_name: "todo-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    #command: "./init.sh"
    expose:
      - "8000"
    ports:
      - "8000:8000"

  ###############
  # Setup client container
  ###############
  frontend:
    image: todotestcg.azurecr.io/todo-test-frontend
    container_name: "todo-frontend"
    # environment:
      # - BACKEND_URL="todo-backend"
    env_file:
      - ./frontend/frontend.env
    build:
      context: ./frontend
    #command: "./entry_point.sh"
    expose:
      - "80"
    ports:
      - "80:3000"
    