version: "3.9"

services:
  backend:
    image: todo-test
    container_name: "todo_backend"
    build:
      context: .
      dockerfile: Dockerfile
    #command: "./init.sh"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    